#!/usr/bin/env python3
"""CloudNova AI-assisted IaC review using Azure OpenAI or OpenAI.

Provider selection:
- Azure OpenAI  — set AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, AZURE_OPENAI_DEPLOYMENT
- OpenAI (public) — set OPENAI_API_KEY (optionally OPENAI_MODEL)
Azure is preferred when AZURE_OPENAI_ENDPOINT is present."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

SYSTEM_PROMPT = """You are a senior DevOps engineer at CloudNova, a mid-size SaaS company.
The team deploys Terraform 20+ times per week. Review rushed infrastructure PRs before merge.

Be specific: cite exact Terraform resources, attribute names, and line-level risks.
Reference CloudNova's past public-storage incident when relevant.
Prioritize exploitable security issues, then cost waste, then governance/naming.

Output valid GitHub-flavored Markdown only — no preamble outside the template."""

USER_PROMPT_TEMPLATE = """Review this Terraform template for CloudNova.

## Governance standards (JSON)
```json
{standards_json}
```

## Checkov policy scan (excerpt)
```
{checkov_excerpt}
```

## Terraform template (`{template_path}`)
```hcl
{terraform_code}
```

## Required response format
Produce Markdown using this structure exactly:

## CloudNova — AI-Assisted IaC Review

<emoji> **Status: <BLOCKED|WARNING|ADVISORY|READY>** — <one sentence summary>

**Template reviewed:** `{template_path}`

### Detected issues

| Severity | Category | Issue | Recommendation |
|----------|----------|-------|----------------|
| ... one row per finding ... |

### Pattern matches in template

- bullet list of concrete anti-patterns found in the code

### Checkov policy scan (excerpt)

```
<repeat or summarize the Checkov excerpt if useful>
```

### CloudNova naming standard

Expected pattern: `<pattern from standards>`

### Next steps

1. numbered actionable steps for the PR author

### Estimated monthly savings (CAD)

- bullet list with rough CAD estimates when cost issues are found

_Generated by `scripts/ai_review.py` (OpenAI) in the CloudNova CI pipeline._

## Status rules
- BLOCKED 🚫: any CRITICAL finding
- WARNING ⚠️: no CRITICAL, but HIGH severity issues remain
- ADVISORY ℹ️: only MEDIUM/LOW issues
- READY ✅: no material issues

Use severity labels CRITICAL, HIGH, MEDIUM, LOW in the table."""


def load_standards(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text())
    return {}


def build_user_prompt(
    template_path: Path,
    terraform_code: str,
    standards: dict,
    checkov_excerpt: str | None,
) -> str:
    convention = standards.get("namingConvention", {}).get("pattern", "cn-{appName}-{resourceType}")
    standards_payload = {**standards, "_expected_naming_pattern": convention}
    return USER_PROMPT_TEMPLATE.format(
        standards_json=json.dumps(standards_payload, indent=2),
        checkov_excerpt=checkov_excerpt.strip() if checkov_excerpt else "(not provided)",
        template_path=template_path,
        terraform_code=terraform_code,
    )


def build_client_and_model():
    """Return (client, model) for Azure OpenAI or public OpenAI based on env vars."""
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")

    if azure_endpoint:
        try:
            from openai import AzureOpenAI
        except ImportError as exc:
            raise RuntimeError("Install the OpenAI SDK: pip install openai") from exc

        api_key = os.getenv("AZURE_OPENAI_API_KEY")
        if not api_key:
            raise RuntimeError("AZURE_OPENAI_API_KEY is not set")

        client = AzureOpenAI(
            api_key=api_key,
            api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2025-04-01-preview"),
            azure_endpoint=azure_endpoint,
        )
        # For Azure, the model argument is the deployment name.
        model = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
        return client, model

    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("Install the OpenAI SDK: pip install openai") from exc

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("Set AZURE_OPENAI_ENDPOINT (+ key/deployment) or OPENAI_API_KEY")

    client = OpenAI(api_key=api_key)
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    return client, model


def run_openai_review(user_prompt: str) -> str:
    client, model = build_client_and_model()

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]

    # A low temperature keeps reviews deterministic, but newer reasoning models
    # (e.g. the gpt-5 family) only accept the default temperature. Retry without
    # it if the model rejects the override.
    try:
        response = client.chat.completions.create(
            model=model,
            temperature=0.2,
            messages=messages,
        )
    except Exception as exc:  # noqa: BLE001 - narrow via message inspection below
        if "temperature" not in str(exc).lower():
            raise
        response = client.chat.completions.create(
            model=model,
            messages=messages,
        )

    content = response.choices[0].message.content
    if not content:
        raise RuntimeError("Model returned an empty response")
    return content.strip()


def parse_status(markdown: str) -> tuple[str, int]:
    match = re.search(r"\*\*Status:\s*(BLOCKED|WARNING|ADVISORY|READY)\*\*", markdown, re.IGNORECASE)
    status = match.group(1).upper() if match else "BLOCKED"
    critical_count = len(re.findall(r"\|\s*CRITICAL\s*\|", markdown, re.IGNORECASE))
    return status, critical_count


def main() -> None:
    parser = argparse.ArgumentParser(description="Run CloudNova AI IaC review via OpenAI")
    parser.add_argument("--template", type=Path, required=True, help="Terraform file to review")
    parser.add_argument("--standards", type=Path, required=True, help="Naming/governance standards JSON")
    parser.add_argument("--checkov-file", type=Path, default=None, help="Optional Checkov output file")
    parser.add_argument("--output", type=Path, default=None, help="Write Markdown review to this file")
    parser.add_argument("--fail-on-critical", action="store_true", help="Exit 1 when CRITICAL issues are found")
    args = parser.parse_args()

    if not args.template.exists():
        print(f"Template not found: {args.template}", file=sys.stderr)
        sys.exit(1)

    standards = load_standards(args.standards)
    terraform_code = args.template.read_text()
    checkov_excerpt = (
        args.checkov_file.read_text()
        if args.checkov_file and args.checkov_file.exists()
        else None
    )

    try:
        user_prompt = build_user_prompt(args.template, terraform_code, standards, checkov_excerpt)
        markdown = run_openai_review(user_prompt)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)

    status, critical_count = parse_status(markdown)

    if args.output:
        args.output.write_text(markdown + "\n")
    else:
        print(markdown)

    if args.fail_on_critical and (status == "BLOCKED" or critical_count > 0):
        sys.exit(1)


if __name__ == "__main__":
    main()
